### ISSUE TITLE
[BUG] canceling context during proxy connection causes application to crash

### ISSUE THREAD

**Issue by VegieIsCute** [Noooste/azuretls-client#40]
**Describe the bug**
When azuretls is created with a context and a proxy is set. The context can be canceled. if the context is canceled it always functions as intended, however, during proxy connection, if the context is canceled the entire application fails due to a memory error.

**To Reproduce**
```
stop := make(chan bool)

	for i := 0; i <= 5; i++ {
		go func() {
			ctx, cancel := context.WithCancel(context.Background())

			go func() {
				<-stop
				cancel()
			}()

			session := azuretls.NewSessionWithContext(ctx)
			defer session.Close()
			if err := session.SetProxy("http://YOUR_PROXY"); err != nil {
				fmt.Println("failed setting proxy")
				return
			}

			response, err := session.Get("https://testfile.org/files-5GB")

			if err != nil {
				fmt.Println(err)
			} else {
				fmt.Println(response.StatusCode, string(response.Body))
			}
		}()
	}

	fmt.Println("press any key to cancel")
	reader := bufio.NewReader(os.Stdin)
	_, _, _ = reader.ReadRune()
	stop <- true
	time.Sleep(1 * time.Hour)

```

Use a somewhat slow proxy and press a key to cancel. If the client is still connecting to the proxy, it will crash, however if the client has finished the connection, it will cancel without crashing the app.

**Expected behavior**
The request should cancel safely even when connecting to a proxy.

**Screenshots**
![image](https://github.com/Noooste/azuretls-client/assets/49800712/73411544-f9af-4ba7-b223-1b375aac2f9e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 120

**Comment by VegieIsCute** [comment]
Here is more information about the bug, it seems to be caused when session.Close() is called because of the defer statement, this attempts to close all connections for the session, including TLS connections. However due to the proxy, the TLS connection hasn't been established yet, and tracing the stack error leads us to the client trying to close a connection that hasn't even been set yet.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x9ffe6a]

goroutine 10 [running]:
github.com/Noooste/utls.(*Conn).Close(0xc0001c6f78?)
        C:/Users/admin/go/pkg/mod/github.com/!noooste/utls@v1.2.5/conn.go:1443 +0xca
github.com/Noooste/azuretls-client.(*Conn).Close(0xc0001bc000)
        C:/Users/admin/go/pkg/mod/github.com/!noooste/azuretls-client@v1.2.12/connection.go:205 +0x27
github.com/Noooste/azuretls-client.(*ConnPool).Close(0xc00019a020)
        C:/Users/admin/go/pkg/mod/github.com/!noooste/azuretls-client@v1.2.12/connection.go:92 +0xb4
github.com/Noooste/azuretls-client.(*Session).Close(0xc00018e1a0)
        C:/Users/admin/go/pkg/mod/github.com/!noooste/azuretls-client@v1.2.12/session.go:394 +0x25
panic({0xb3b2e0?, 0xea5830?})
```
