### ISSUE TITLE
[BUG] Header And Order In Param 

### ISSUE THREAD

**Issue by musicyin** [Noooste/azuretls-client#69]
```
	session := azuretls.NewSession()
	defer session.Close()

	orders := azuretls.HeaderOrder{"cache-control", "sec-ch-ua", "sec-ch-ua-mobile", "sec-ch-ua-platform", "upgrade-insecure-requests", "user-agent", "accept", "sec-fetch-site", "sec-fetch-mode", "sec-fetch-user", "sec-fetch-dest", "accept-encoding", "accept-language"}
	headers := http.Header{
		"accept":                    {"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"},
		"accept-encoding":           {"gzip, deflate, br"},
		"accept-language":           {"zh-HK,zh-TW;q=0.9,zh;q=0.8"},
		"cache-control":             {"max-age=0"},
		"sec-ch-ua":                 {`"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"`},
		"sec-ch-ua-mobile":          {"?0"},
		"sec-ch-ua-platform":        {`"Windows"`},
		"sec-fetch-site":            {"none"},
		"sec-fetch-mode":            {"navigate"},
		"sec-fetch-user":            {"?1"},
		"sec-fetch-dest":            {"document"},
		"user-agent":                {"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"},
		"upgrade-insecure-requests": {"1"},
	}

	response, err := session.Get("https://jigsaw.w3.org/HTTP/300/302.html", headers, orders)

	if err != nil {
		panic(err)
	}
	fmt.Println(string(response.Body))
```

Error:
```
panic: assignment to entry in nil map                                                                      
                                                                                                           
goroutine 1 [running]:                                                                                     
github.com/Noooste/azuretls-client.(*Session).makeHeadersCopier.func1(0xc0002b2000)                        
        C:/Users/Administrator/go/pkg/mod/github.com/!noooste/azuretls-client@v1.4.5/header.go:240 +0x191  
github.com/Noooste/azuretls-client.(*Session).do(0xc0000e4340, 0xc000002180, {0xc0000d1e88, 0x2, 0x2})     
        C:/Users/Administrator/go/pkg/mod/github.com/!noooste/azuretls-client@v1.4.5/session.go:311 +0x3f1 
github.com/Noooste/azuretls-client.(*Session).Get(0xc0000e4340, {0x777698, 0x27}, {0xc0000d1e88, 0x2, 0x2})
        C:/Users/Administrator/go/pkg/mod/github.com/!noooste/azuretls-client@v1.4.5/session.go:378 +0x96  
main.main()                                                                                                
        C:/awesomeProject2/main.go:47 +0xaa9
```

How to trigger an error:
When we pass headers and headerorder and get a page that 302 redirect , it panic.

**Comment by Noooste** [comment]
Hello, thanks for this report, it's now fixed. 
I advise you to use azuretls.OrderedHeaders to reduce code size.
