### ISSUE TITLE
[BUG] Issue with 403 Status Code Page [NOT FIX]

### ISSUE THREAD

**Issue by musicyin** [Noooste/azuretls-client#76]
```
	session := azuretls.NewSession()
	defer session.Close()

	_ = session.SetProxy("socks5://127.0.0.1:30001") // you should use charles proxy to see this issue
	session.InsecureSkipVerify = true

	headers := http.Header{
		"user-agent": {"robot"}, //use robot user-agent to make issue
	}

	for {
		req := &azuretls.Request{
			Method:           http.MethodGet,
			Url:              "https://driverpracticaltest.dvsa.gov.uk/",  //I cannot find other website protected by incapsula , just use this to test
			Header:           headers,
			DisableRedirects: true,
		}

		response, err := session.Do(req)

		if err != nil {
			fmt.Println(err.Error())
		} else {
			fmt.Println(response.StatusCode)
			fmt.Println(string(response.Body))
		}
		time.Sleep(2 * time.Second) //Prevent attack the website
	}
```

Error Details:
```
http2: timeout awaiting response headers
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x12b7c51]                    
                                                                       
goroutine 1 [running]:                                                 
github.com/Noooste/fhttp.(*Request).Cookies(...)                       
        C:/Users/Administrator/go/pkg/mod/github.com/!noooste/fhttp@v1.0.11/request.go:412
github.com/Noooste/azuretls-client.(*Session).makeHeadersCopier(0xc0000e4340, 0xc000294000)
        C:/Users/Administrator/go/pkg/mod/github.com/!noooste/azuretls-client@v1.4.9/header.go:197 +0x2f1
github.com/Noooste/azuretls-client.(*Session).do(0xc0000e4340, 0xc000294000, {0x0, 0x0, 0x0})
        C:/Users/Administrator/go/pkg/mod/github.com/!noooste/azuretls-client@v1.4.9/session.go:269 +0x251
github.com/Noooste/azuretls-client.(*Session).Do(...)
        C:/Users/Administrator/go/pkg/mod/github.com/!noooste/azuretls-client@v1.4.9/session.go:239
```

Expect:
Status code and content should be response correctly

Remark:
You may need to use a non-US IP to trigger this status code
The second request cannot be sent and no error is reported.
Appears after 30 seconds, http2: timeout awaiting response headers
But the actual request was not sent (Charles can clearly see that the request was not sent)

**Comment by musicyin** [comment]
After tracing , it seems there is a problem in [line193 : session.go]
httpResponse, err = roundTripper.RoundTrip(request.HttpRequest)

**Comment by musicyin** [comment]
```
func (c *Conn) checkTLS() bool {
	if c.TLS == nil {
		return false
	} else if c.TLS.ConnectionState().VerifiedChains != nil {
		state := c.TLS.ConnectionState()
		for _, peerCert := range state.PeerCertificates {
			if time.Now().After(peerCert.NotAfter) {
				// the certificate is expired, so we need to create a new connection
				return false
			}
		}
	} else if c.Conn == nil {
		return false
	}
	_, ok := c.Conn.(*net.TCPConn)
	if !ok { // if the connection is dead 
		return false
	}
	return true
}
```
`func (c *Conn) makeTLS(addr string) error {
	if c.checkTLS() {
		return nil
	}
	return c.NewTLS(addr)
}`

After I modified it, the problem was solved.
And print error "Use a closed network connection" successfully
Do you think this modification will cause any problems?

**Comment by Noooste** [comment]
Hello, thank you for trying to solve this problem. Open a PR, we'll see if it doesn't break other things.

**Comment by Noooste** [comment]
All seems to work, it has been merged 👍
